<?php $id=$_POST['valor'];
$tabla=$_POST['tabla'];
if ($tabla=="Zona") {
	$respuesta = $con->seZonaId($id);
	$resultados_row = $con->fetch_array($respuesta);
	print('<td d-c="Zona">'.$resultados_row['zona'].'</td><td d-c="Nivel">'.$resultados_row['nivel'].'</td><td d-c="Subsistema">'.$resultados_row['subsistema'].'</td><td d-c="Actualizar"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/frm/Zona/'.$resultados_row['id_zona'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/actualizar.png" class="ifo" title="Actualizar" alt=""></a></td><td d-c="Eliminar"><a href="#" onclick="eliminarZona(\''.$resultados_row['id_zona'].'\',\''.$resultados_row['zona'].'\')"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/eliminar.png" class="ifo" ></a></td>');
}else if($tabla=="Supervision"){
	$respuesta = $con->seSupervisionBusc('cct',$id);
	$resultados_row = $con->fetch_array($respuesta);
	print('<td d-c="CCT">'.$resultados_row['cct'].'</td> <td d-c="Sede">'.$resultados_row['sede'].'</td><td d-c="Oficina">'.$resultados_row['oficina'].'</td><td d-c="Escuelas">'.$resultados_row['num_escuelas'].'</td><td d-c="Grupos">'.$resultados_row['num_grupos'].'</td><td d-c="Alumnos">'.$resultados_row['num_alumnos'].'</td><td d-c="Zona">'.$resultados_row['zona'].'</td><td d-c="Actualizar"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/frm/Supervision/'.$resultados_row['cct'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/actualizar.png" class="ifo" title="Actualizar" alt=""></a></td><td d-c="Eliminar"><a href="#" onclick="eliminarSupervision(\''.$resultados_row['cct'].'\')"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/eliminar.png" class="ifo"></a></td>');
}else if($tabla=="Escuela"){
	$respuesta = $con->seEscuelaBusc('cct',$id);
	$resultados_row = $con->fetch_array($respuesta);
	print('<td d-c="CCT">'.$resultados_row['cct'].'</td><td d-c="Nombre">'.$resultados_row['nombre'].'</td><td d-c="Director">'.$resultados_row['director'].'</td><td d-c="Subdirector">'.$resultados_row['subdirector'].'</td><td d-c="Subsistema">'.$resultados_row['subsistema'].'</td><td d-c="Org Social">'.$resultados_row['org_social'].'</td><td d-c="Turno">'.$resultados_row['turno'].'</td><td d-c="Codigo Postal">'.$resultados_row['codigo_postal'].'</td><td d-c="Asentamiento">'.$resultados_row['nom_asentamiento'].'</td><td d-c="Act.Ubicacion"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/frm/Ubicacion/'.$resultados_row['cct'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/actualizarUbica.png" class="ifo"></a></td><td d-c="Contacto"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/detalles/'.$resultados_row['cct'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/mapa.jpg" class="ifo"></a></td><td d-c="Actualizar"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/frm/Escuela/'.$resultados_row['cct'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/actualizar.png" class="ifo"></a></td><td d-c="Eliminar"><a href="#" onclick="eliminarEscuela(\''.$resultados_row['cct'].'\')"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/eliminar.png" class="ifo"></a></td>');
}else if ($tabla=="Personal" ) {
	$respuesta = $con->sePersonalBusc('rfc',$id);
	$resultados_row = $con->fetch_array($respuesta);
	print('<td d-c="RFC">'.$resultados_row['rfc'].'</td><td d-c="Nombre(s)">'.$resultados_row['nombre'].'</td><td d-c="Apellido Paterno">'.$resultados_row['a_paterno'].'</td><td d-c="Apellido Materno">'.$resultados_row['a_materno'].'</td><td d-c="Funcion">'.$resultados_row['funcion'].'</td><td d-c="Administrar Escuelas"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/personalEsc/'.$resultados_row['rfc'].'" id="btnPersonalEsc" tabla="PersonalEsc"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/images/actualizarEsc.png" class="ifo" title="Administrar Escuelas" alt=""></a></td><td d-c="Actualizar"><a href="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca/frm/Personal/'.$resultados_row['rfc'].'"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/actualizar.png" class="ifo" title="Actualizar" alt=""></a></td><td d-c="Eliminar"><a href="#" onclick="eliminarPersonal(\''.$resultados_row['rfc'].'\')"><img src="http://'.$_SERVER['SERVER_ADDR'].'/ixtapaluca'.'/images/eliminar.png" class="ifo" title="Eliminar" alt=""></a></td>');
}
?>